apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumen-api
  labels:
    app: blog
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
      tier: app
  template:
    metadata:
      labels:
        app: blog
        tier: app
    spec:
      containers:
        - name: api
          image: aronnebrivio/php:8.0-k8s
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: api
          env:
            - name: DB_HOST
              value: $(MYSQL_SERVICE_HOST)
            - name: DB_HOST_READONLY
              value: $(MYSQL_RO_SERVICE_HOST)
            - name: DB_PORT
              value: $(MYSQL_SERVICE_PORT)
            - name: REDIS_HOST
              value: $(REDIS_SERVICE_HOST)
            - name: REDIS_PORT
              value: $(REDIS_SERVICE_PORT)
      initContainers:
        - name: init-wait
          image: alpine
          env:
            - name: DB_HOST
              value: $(MYSQL_SERVICE_HOST)
            - name: DB_PORT
              value: $(MYSQL_SERVICE_PORT)
          command:
            - sh
            - "-c"
            - |
            - echo "Connecting to $DB_HOST $DB_PORT ..."
            - "for i in $(seq 1 300); do nc -zvw1 $DB_HOST $DB_PORT && exit 0 || sleep 3; done; exit 1"
        - name: database-migrations
          image: aronnebrivio/php:8.0-k8s
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: $(MYSQL_SERVICE_HOST)
            - name: DB_HOST_READONLY
              value: $(MYSQL_RO_SERVICE_HOST)
            - name: DB_PORT
              value: $(MYSQL_SERVICE_PORT)
            - name: REDIS_HOST
              value: $(REDIS_SERVICE_HOST)
            - name: REDIS_PORT
              value: $(REDIS_SERVICE_PORT)
          command:
            - bash
            - "-c"
            - |
            - env
            - "cd /var/www/html && php artisan migrate:fresh --seed"
