apiVersion: v1
kind: Service
metadata:
  name: data-tier
  labels:
    app: blog
spec:
  ports:
    - port: 6379
      name: redis
    - port: 3306
      name: mysql
  selector:
    tier: data
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-tier
  labels:
    tier: data
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: data
  template:
    metadata:
      labels:
        tier: data
        app: blog
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis

        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: blog_development
